name: Android apk generation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build with espresso build 
      run: ./gradlew assembleAndroidTest
    - uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
    - uses: actions/upload-artifact@v3
      with:
        name: espresso-test-apk
        path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
    - name: check the folder path
      run: ls
    - name: upload test file
      run: |
            API_RESPONSE=$(curl -u "pradapjackiejack1:SmRsFRzByBRXzHxsFy6z" \ -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/app" \-F "file=@app/build/outputs/apk/debug/app-debug.apk");
            echo $API_RESPONSE
    - name: upload instrumentation file
      run: | 
            curl -u "pradapjackiejack1:SmRsFRzByBRXzHxsFy6z" \ -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/test-suite" \-F "file=@app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"
    - name: final test
      run: |
            echo "$API_RESPONSE"
